sudo: required
dist: trusty
language: cpp
compiler: clang
services: docker

before_install: "./scripts/setup_env.sh"
install: "./scripts/build_all.sh"

script:
- "./scripts/test_all.sh"

deploy:
  provider: releases
  api_key:
    secure: hjHHZgluWyf+a9jLuSmTKEaMiDdZX/tM71q59Z7ctSNCWTQhEp3vn/gSRHrbrTWPk0N/mQNkfq/6l51m5eRMuKboMZbPj9H87AJHJn1fKQmmq05d7joq6mKVAzoqMH4Pde1i7NqkJpJLW5PbFIY24nKy7g3FeqnFrp36oUxFTsee0XLt3waYv6COhEDNXyzoUIMP/qdjh2nxXXMeE9hE9R3YUOBrYSehSPxSKY2IFbzPi/q8Gqyw8L2YKem+tbS7T3tGBZnADufZrorENybuUCtIQtcV+n0eiqfVw7yI+QmiFWLtOKV4yM3exnxjKZbB0yG1lA3JCeUvt+6OtxxXMXuktZkgRdWFQHKBji+F/WHhq8LYt7st24wbDz4zGsw3p9GB65OccvFkdOm06cJMRQcPp6AzJELJ4poxLTRnsiURM4hjwjwYqVHu4YsNNK9Umia/4jpUBpTmFGzhalC18mSJqBvpLGkim89IhRSiRbhTix+tK/liER7FDcWBFdAsReXUEfgUUt+BW2Q4aXdQP7ZEtemxvO3K2IAc46pdgzIDv8tQB5BWhm+eUH5ZG+xHIim2tzdxKg0PVy4offSGZfeBQHAslQqWh6QgqS5mJ3aEPY3cruFhAm1Sv3NQzSy493D4WfDF6l7jf379Y4E2yhW4H/h7Nd+iMGx6wYqaSfk=
  skip_cleanup: true
  file_glob: true
  file: trinitycore-module*.tar.gz
  on:
    repo: dgonzalezruiz/nami-trinitycore
    tags: true
    all_branches: true

env:
  global:
  - WORLD_SQL=TDB_full_335.62_2016_10_17
  - WORLD_SQL_URL=https://github.com/TrinityCore/TrinityCore/releases/download/TDB335.62/$WORLD_SQL.7z
  - MAPS_URL=https://github.com/dgonzalezruiz/docker-trinitycore/releases/download/Assets-986d830ae7b4/data-986d830ae7b4.tar.gz
  - secure: yIsGuuLVnwbjXqIc5/Lt/K+v8OOmHCvhGTNtkoROc2thhJsowvuM6rEgdx5WNJKK+yQR3aEFMc2lU/A0WSVFXg/Tzgl2BRIH7vOq6n3KcK4hd1tt4z3rHTzWa2rZ6m3wXMhVXsYLyxNhYYj//QrZBjH4692MpqGiOMPplqwuTcMor46/VBuvjf60PUlaGnvpHNb192SMlKQ/fkrIoN4vxDpQIZoS7StJeUPzq7FaoN/g2YGfaKTmEZ4ZpD2qcROAL8qo8tq3S/lFZOIQDG4mGK6h+Z3EIpOGkfgASo3Txl5HtpHLWqQL4DRMg9IqMkvJgMaLg+s2D8HZY4JF1F2W2v9ahYpHP/GmAqqs9/dWfiOkuQ6MUivBLo/2m0xPad5f9mK54Kn0W0P7JY5VpLNFuwLTJgYHptIpPHBKKC8rFMoCYgy6OCq3lQ7y4ltJHIlN6j8tgz9lKPmczg5QQRyJXn4b7Vy4ay3R5RT9sotgZCrQCZeI4AnULoRuyjIGwb5lkxY7enbCaGqNp1bA5v+0PktTfkCEYA8uEDnH/3MdzRNEIH746YsK14g/zLv7mWsfREVHhUOZAI1+FeaFjRloVfKgxzW1ayp8b6xIyyiw1p8yz9vltwEFMDpZ9CFCWce/zLWzMETHifLQJvxvakWnz2FKz5Quz9L38Q5gkoxVJtY=
