sudo: required
dist: trusty
language: cpp
compiler:
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget p7zip
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - sudo apt-get -qq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev libboost-regex1.55-dev
script: 
  - ./helper_scripts/build_all.sh 
services: docker
deploy:
  provider: releases
  api_key:
    secure: TMXW7uSuzuThBJ26sY0kcu9nZyZrpZjv8GF3/N7wqBCkFfnVUr8NfEwqWfFGvIDMPNBBMqNVql8fCDnOVDjFjM2QSpCo06pi4evhhlGuh/J78nBMEVeZSJm5U2yARjNVJ/oXwhR4L9HwesLIfiu9zugIph79xE6R6tXvhNm8HRXNEXqznGVnhYP/+LAVlimh5IVENMnuz3H15+/OJZDCbRmjCBYgqA+mtbQ0ejpMONE6Q44FF45p2L6tQOl9g0C5vcNTHKzj8iS/XQpuDG0uxTQEewZTfCeniQ+qGaejW5afPH9T3oQ+LSUgVwQHrIkeIcSFdS++w/LAezHMGWOkNzADxvQg3w070Nneo0PxwYUupHE4MxBhB9p/NaQgVPmKqqkGn1mQ4YCgaChseM6FIUOhjTx9mmBJURO0Rn4U9kL/8PgyIdkEOOAA99curcY3/bFqkvX4DC8dMdJVfh8s8GlfPqY4MlR1gWurNLqtFTy4jNs8CQOx5QGmtZvSbztVT/g6TuORcSNbtkYUU0k3xfdsE0JdiGika/nYYX/MjgnO3mYpI/NqvBxQJFyu/XnMy246vjdkHdqylpaQpLCstH4UW8fjVJgH4E7kU1G9myVEScRM0nKOkFjMGjyWICzMOG3mxY53mb37dOlGAkeebAN4F0DvKDaYyqLBqsczPUw=
  file: trinitycore-module*.tar.gz
  on:
    repo: dgonzalezruiz/nami-trinitycore
