sudo: required
dist: trusty

cache:
  timeout: 500
  directories:
  - trinitycore

language: cpp
compiler: clang
services: docker

before_install: "./scripts/setup_env.sh"
install: "./scripts/build_all.sh"

script:
- "./scripts/test_all.sh"

after_failure:
- "./script/tag_deletion.sh"

deploy:
  provider: releases
  api_key:
    secure: hjHHZgluWyf+a9jLuSmTKEaMiDdZX/tM71q59Z7ctSNCWTQhEp3vn/gSRHrbrTWPk0N/mQNkfq/6l51m5eRMuKboMZbPj9H87AJHJn1fKQmmq05d7joq6mKVAzoqMH4Pde1i7NqkJpJLW5PbFIY24nKy7g3FeqnFrp36oUxFTsee0XLt3waYv6COhEDNXyzoUIMP/qdjh2nxXXMeE9hE9R3YUOBrYSehSPxSKY2IFbzPi/q8Gqyw8L2YKem+tbS7T3tGBZnADufZrorENybuUCtIQtcV+n0eiqfVw7yI+QmiFWLtOKV4yM3exnxjKZbB0yG1lA3JCeUvt+6OtxxXMXuktZkgRdWFQHKBji+F/WHhq8LYt7st24wbDz4zGsw3p9GB65OccvFkdOm06cJMRQcPp6AzJELJ4poxLTRnsiURM4hjwjwYqVHu4YsNNK9Umia/4jpUBpTmFGzhalC18mSJqBvpLGkim89IhRSiRbhTix+tK/liER7FDcWBFdAsReXUEfgUUt+BW2Q4aXdQP7ZEtemxvO3K2IAc46pdgzIDv8tQB5BWhm+eUH5ZG+xHIim2tzdxKg0PVy4offSGZfeBQHAslQqWh6QgqS5mJ3aEPY3cruFhAm1Sv3NQzSy493D4WfDF6l7jf379Y4E2yhW4H/h7Nd+iMGx6wYqaSfk=
  skip_cleanup: true
  file_glob: true
  file: trinitycore-module*.tar.gz
  on:
    repo: dgonzalezruiz/nami-trinitycore
    tags: true
    all_branches: true
env:
  global:
  - WORLD_SQL=TDB_full_335.63_2017_04_18
  - WORLD_SQL_URL=https://github.com/TrinityCore/TrinityCore/releases/download/TDB335.63/$WORLD_SQL.7z
  - MAPS_URL=https://github.com/dgonzalezruiz/docker-trinitycore/releases/download/Assets-986d830ae7b4/data-986d830ae7b4.tar.gz
  - secure: fR0MEWsiHKPKxH2NT6hLg8Wpv0uhXY0qmBt2Msl8jeBHbgRyJdw8t3oFuTDjS8zNxWiB6Q+w7uifIkLuJRIY7NZxLEsdDZjLNeuBgKki1kARfKMFiQ1Wy/r5CR+wlkQYr9an6zcVr0EtlL94s6119kPGTdeJdk/z9w8hR3HJaeH10Ni1ThiBhgCdoArlbafWpKXjZLpOpS35QwCn2z77nQGtfssTP+YWgemlYnOpwMGYYGqFyIoBsurI4b2Ro2gFSRApfjhb7X9kNKzc3nTrjxZ8uQzYCM/Hz1eb8phG0KLrqJJYLFi9Jawo1DsfssL+9oKZLfYJkRInYB3CNhbGFFFqaqxIF8fB2VyW9JIyR3eQMrgecXzG2JlrE0y23OVLiXPS6IzWWEOUe0qoGM7gSs3nf4muBhOLanLEOaMI1tJGzsDQiK1x4EI0d/BzQA31GS+nIM4y0h85eiA/VMnqzdsujtRinQZbvvkN9GyVk1/m0Iw+WxxhVxPr68ErFaGYXkq6M1bM3H6jhX1AoL3Du1GZVHL27xBSPPiMrGo0ofbrq3AGi28eUXzq/bdoaZhrdk5d7yMlpbq3vihsxjMl0cBvHJ7LPHENtODqto5gdTXHHVBtUygAavpNouHvJRIU1w311t1kOd9W3M47RcVB2dNmdoJyfFnRmMv+lzm9YeM=
