sudo: required
dist: trusty
language: cpp
compiler:
  - clang
before_install: sudo apt-get update -qq
install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl p7zip
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - sudo apt-get -qq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev libboost-regex1.55-dev
  - git clone -b 3.3.5 --single-branch https://github.com/TrinityCore/TrinityCore
script: 
  - ./helper_scripts/build_all.sh 
