FROM gcr.io/bitnami-containers/minideb-extras:jessie-r12

MAINTAINER GodBoole <godboole@bitnami.com>

RUN install_packages git libmysqlclient-dev libssl-dev \
                     libbz2-dev libreadline-dev libncurses-dev \ 
                     libboost-all-dev p7zip cmake make \
                     gcc g++

